# Generated by Django 5.0.6 on 2024-06-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DispensarioMedico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('idmedicamentos', models.AutoField(db_column='idMedicamentos', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('dosis', models.TextField(blank=True, db_column='Dosis', null=True)),
                ('estado', models.TextField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Medicamentos',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='marcas',
            options={'managed': True},
        ),
    ]
